### ISSUE TITLE
Please what license do you intend to use on this project?

### ISSUE THREAD

**Issue by carlosdelfino** [mustafa0x/tadwin#1]
Please what license do you intend to use on this project?

I am interested in using it in my Arabic studies.

I am Brazilian, I speak Portuguese, and I learn Arabic through youtube videos in English, and maybe your software will help me make notes where I can use both languages.

Also I can learn more about development with NodeJS, JavaScript and Typescript.

**Comment by mustafa0x** [comment]
The license will be GPL.

Yes, this project requires advanced knowledge of JS. I hope to add a roadmap soon.
